name: test

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: bash

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup architecture and packages
      run: |
        sudo dpkg --add-architecture i386 && sudo apt-get update
        sudo apt-get -y install python3 pipx yq xwallpaper imagemagick wget git stow sudo
        sudo ln -fs /usr/share/zoneinfo/Africa/Libreville /etc/localtime
    - name: Setup Environment
      run: |
        export DEFAULT_PYWAL16_OUT_DIR="$HOME/.cache/wal"
        pipx install pywal16==3.8.10
        mkdir -p "$HOME/Pictures/Wallpapers"
        wget https://raw.githubusercontent.com/aKqir24/.files/refs/heads/main/.config/walset.toml -O "$HOME/.config/walset.toml"
        sed -i -e 's/akqir24/runner/g' -e 's/colorz/wal/g' -e 's/image/none/g' "$HOME/.config/walset.toml" && mkdir -p "$HOME/.config/xsettingsd"
        wget https://raw.githubusercontent.com/aKqir24/.files/refs/heads/main/.config/xsettingsd/xsettingsd.conf -O "$HOME/.config/xsettingsd/xsettingsd.conf" 
        wget https://raw.githubusercontent.com/aKqir24/.files/main/Pictures/Wallpapers/wallpaper.jpg -O "$HOME/Pictures/Wallpapers/wallpaper.jpg"
    - name: Test the program
      run: |
        bash walset.sh --load --verbose && exit 0
