name: test

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: bash

jobs:
  run-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup architecture and packages
      run: |
        sudo dpkg --add-architecture i386 && sudo apt-get update
        sudo apt-get -y install python3 pipx yq xwallpaper imagemagick wget git stow sudo
        sudo ln -fs /usr/share/zoneinfo/Africa/Libreville /etc/localtime
    - name: Setup Environment
      run: |
        export PYWAL_CACHE_DIR="$HOME/.cache/wal"
        export config_repo="https://raw.githubusercontent.com/aKqir24/.files/refs/heads/i3/.config"

        pipx install pywal16
        mkdir -p "$HOME/Pictures/Wallpapers"
        mkdir -p "$HOME/.config/xsettingsd"
        
        wget "$config_repo/walset.toml" -O "$HOME/.config/walset.toml"
        wget "$config_repo/xsettingsd/xsettingsd.conf" -O "$HOME/.config/xsettingsd/xsettingsd.conf" 
        wget https://raw.githubusercontent.com/aKqir24/.files/i3/Pictures/Wallpapers/wallpaper.jpg -O "$HOME/Pictures/Wallpapers/wallpaper.jpg"

        sed -i -e 's/akqir24/runner/g' -e 's/colorz/wal/g' -e 's/image/none/g' "$HOME/.config/walset.toml"
    - name: Test the program
      run: |
        if [ $? -eq 0 ]; then 
          time bash walset.sh --load --debug --verbose
        else  
          echo "Program failed!"
        fi
