name: test

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    shell: bash

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup architecture and packages
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install python3 pipx yq xwallpaper imagemagick wget git stow sudo
        sudo ln -fs /usr/share/zoneinfo/Africa/Libreville /etc/localtime
    - name: Setup Environment
      run: |
        export DEFAULT_PYWAL16_OUT_DIR="$HOME/.cache/wal"
        pipx install pywal16==3.8.10
        git clone https://github.com/aKqir24/.files.git
        cd ".files" && stow . --adopt
        cd "$HOME" && cat .bashrc
    - name: Test the program
      run: |
        bash walset.sh --load --verbose
